version: "3.5"
services:
  bitcoin1: # the miner generating blocks
    image: "bitcoin-abc"
    restart: always
    build:
      context: "./bitcoin-abc"
    command: "bitcoind"
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "bitcoin-cli", "getblockchaininfo"]
    expose:
      - "18333"
    ports:
      - "18444:18443"
    volumes:
      - ./bitcoin-abc/bitcoin.conf:/data/bitcoin.conf
    networks:
      - regnet
  bitcoin2: # the node connected to SLPDB via RPC and zmq
    image: "bitcoin-abc"
    restart: always
    build:
      context: "./bitcoin-abc"
    command: "bitcoind"
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "bitcoin-cli", "getblockchaininfo"]
    expose:
      - "18333"
      - "28332"
    ports:
      - "18443:18443"
    volumes:
      - ./bitcoin-abc/bitcoin.conf:/data/bitcoin.conf
    networks:
      - regnet
  mongo:
    image: mongo:4.2
    restart: always
    networks:
      - regnet
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "devrs" ]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --quiet 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - "26017:27017"
    volumes:
       - ./mongo/db:/data/db
       - ./mongo/configdb:/data/configdb
  slpdb:
    build:
      context: "./slpdb"
    image: slpdb
    restart: always
    networks:
      - regnet
    depends_on:
      - mongo
      - bitcoin2
    ports:
      - "27339:28339"

networks:
  regnet:
